### ISSUE TITLE
Crash on large image filesize

### ISSUE THREAD

**Issue by harleyknd1** [MeshackMusundi/SignalChat#1]
The client crashes when a large image (jpg, png, other) is used when trying to use the application
(Connection started reconnecting before invocation result was received)

**Comment by MeshackMusundi** [comment]
It's not possible to use an image larger than 150x150px. If you attempt to do so this bit of code in the `SelectPhoto()` function will show you a dialog box alerting you to this fact,

```
if (img.Width > MAX_IMAGE_WIDTH || img.Height > MAX_IMAGE_HEIGHT)
{
   dialogService.ShowNotification($"Image size should be {MAX_IMAGE_WIDTH} x {MAX_IMAGE_HEIGHT} or less.");
   return;
}
```
